---
- name: Updating docker
  hosts: all
  gather_facts: false

  tasks:
    - name: Update and (re)start services
      community.docker.docker_compose_v2:
        project_src: "{{ lookup('env','HOME') }}/{{ docker_project_src }}"
        pull: policy
        build: policy
        state: present
        recreate: auto