---
- name: Updating docker
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Update and (re)start services
      community.docker.docker_compose_v2:
        project_src: "/var/services/homes/{{ docker_project_src }}"
        docker_cli: "{{ docker_cli }}"
        pull: always
        build: policy
        state: present
        recreate: auto