---
- name: Patching and Updating Linux Systems
  hosts: all
  become: true

  tasks:
    - name: Update Debian-based Systems
      when: ansible_os_family == 'Debian'
      apt:
        update_cache: true
        upgrade: safe
        autoremove: true

    - name: Update RHEL-based Systems
      when: ansible_os_family == 'RedHat'
      dnf:
        name: '*'
        state: latest
        update_cache: true
    
    - name: Autoremove unneeded packages installed as dependencies
      when: ansible_os_family == 'RedHat'
      dnf:
        autoremove: yes

    - name: Update Alpine-based Systems
      when: ansible_os_family == 'Alpine'
      apk:
        update_cache: true
        upgrade: true
